{{- if .Values.enabled -}}
{{- $tracingEnabled := include "gpkg-terrain.tracingEnabled" . -}}
{{- $tracingUrl := include "gpkg-terrain.tracingUrl" . -}}
{{- $metricsEnabled := include "gpkg-terrain.metricsEnabled" . -}}
{{- $metricsUrl := include "gpkg-terrain.metricsUrl" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: {{ $tracingEnabled | quote }}
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: {{ $metricsEnabled | quote }}
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
  GPKG_LIST: {{ .Values.env.gpkgList | quote }}
{{- end }}
